DAPNETGATEWAY_VERSION = 631297ece7f9596755434f1bb2a8a11772a5e922
DAPNETGATEWAY_SITE = https://github.com/g4klx/DAPNETGateway
DAPNETGATEWAY_SITE_METHOD = git
DAPNETGATEWAY_LICENSE = GPLv2

define DAPNETGATEWAY_BUILD_CMDS
	$(MAKE) CC="$(TARGET_CC)" CXX="$(TARGET_CXX)" LD="$(TARGET_LD)" -C $(@D)
endef

define DAPNETGATEWAY_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 $(@D)/DAPNETGateway $(TARGET_DIR)/usr/bin/DAPNETGateway
	$(INSTALL) -m 0644 $(@D)/DAPNETGateway.ini $(TARGET_DIR)/etc/DAPNETGateway.ini
endef

$(eval $(generic-package))
